name: Mutate

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch: {}

jobs:
  mutate:
    strategy:
#       matrix:
#         args:
#           - '--build-arg n_mutations=500 --build-arg modules="src/burrow.ml src/cfmm.ml src/checker.ml src/checkerMain.ml src/common.ml src/constants.ml"'
#           - '--build-arg n_mutations=500 --build-arg modules="src/fa2Interface.ml src/lqt.ml src/parameters.ml"'
#           - '--build-arg n_mutations=50  --build-arg modules="src/liquidationAuction.ml src/sliceList.ml src/mem.ml src/ptr.ml"'
#           - '--build-arg n_mutations=50  --build-arg modules="src/avl.ml"'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#         with:
#           submodules: recursive
#       - name: Add git branch for earthly
#         run: |
#           branch=""
#           if [ -n "$GITHUB_HEAD_REF" ]; then
#             branch="$GITHUB_HEAD_REF"
#           else
#             branch="${GITHUB_REF##*/}"
#           fi
#           git checkout -b "$branch" || true
#       # FIXME: Might need to swap to a PAT here since GITHUB_TOKEN is still unreliable
#       #   See: https://github.community/t/403-error-on-container-registry-push-from-github-action/173071
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Install earthly
#         run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.23/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
#       - name: Run mutation tests
#         run: earthly --ci ${{matrix.args}} +test-mutations
